name: "Validate code stability"
on: [push]
jobs:
  test-application:
    runs-on: ubuntu-22.04
    steps:
      - name: "Say hello"
        run: echo "Hello"
        
      - name: "Say Good bye"
        run: echo "Good bye"
